/* Generated By:JJTree: Do not edit this line. ASTColumnDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTColumnDef extends SimpleNode {
  public ASTColumnDef(int id) {
    super(id);
  }

  public ASTColumnDef(RookieParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fce10bf8bf9bc6f286a96e8e0e585bc3 (do not edit this line) */
