/* Generated By:JJTree: Do not edit this line. ASTFunctionCallExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTFunctionCallExpression extends SimpleNode {
  public ASTFunctionCallExpression(int id) {
    super(id);
  }

  public ASTFunctionCallExpression(RookieParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0c5ef5f41c059bb5997e66dcf892fa2c (do not edit this line) */
