/* Generated By:JJTree: Do not edit this line. ASTLogicalExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTLogicalExpression extends SimpleNode {
  public ASTLogicalExpression(int id) {
    super(id);
  }

  public ASTLogicalExpression(RookieParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=94b8ceb3092c99d205fcf8ae3034e8af (do not edit this line) */
