/* Generated By:JJTree: Do not edit this line. ASTSQLStatementList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTSQLStatementList extends SimpleNode {
  public ASTSQLStatementList(int id) {
    super(id);
  }

  public ASTSQLStatementList(RookieParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b55826e399c6caf4f17c8a1be0b6633 (do not edit this line) */
