/* Generated By:JJTree: Do not edit this line. ASTUpdateStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.berkeley.cs186.database.cli.parser;

public
class ASTUpdateStatement extends SimpleNode {
  public ASTUpdateStatement(int id) {
    super(id);
  }

  public ASTUpdateStatement(RookieParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public void jjtAccept(RookieParserVisitor visitor, Object data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d8aeb9f55eb5e33b4a8bca0ebcecfa4c (do not edit this line) */
