/* RookieParserTokenManager.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. RookieParserTokenManager.java */
package edu.berkeley.cs186.database.cli.parser;

/** Token Manager. */
public class RookieParserTokenManager implements RookieParserConstants {
  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40L) != 0L)
            return 1;
         if ((active0 & 0x1fffffffff800000L) != 0L)
         {
            jjmatchedKind = 66;
            return 11;
         }
         return -1;
      case 1:
         if ((active0 & 0x1040029004000000L) != 0L)
            return 11;
         if ((active0 & 0xfbffd6ffb800000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 66;
               jjmatchedPos = 1;
            }
            return 11;
         }
         return -1;
      case 2:
         if ((active0 & 0x1fbdfd2f7b800000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 2;
            return 11;
         }
         if ((active0 & 0x2004080000000L) != 0L)
            return 11;
         return -1;
      case 3:
         if ((active0 & 0x400100a23000000L) != 0L)
            return 11;
         if ((active0 & 0x1bbded2558800000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 3;
            return 11;
         }
         return -1;
      case 4:
         if ((active0 & 0x1201a52400800000L) != 0L)
            return 11;
         if ((active0 & 0x9bc480158000000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 4;
            return 11;
         }
         return -1;
      case 5:
         if ((active0 & 0x9b8000000000000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 5;
            return 11;
         }
         if ((active0 & 0x4480158000000L) != 0L)
            return 11;
         return -1;
      case 6:
         if ((active0 & 0x38000000000000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 6;
            return 11;
         }
         if ((active0 & 0x980000000000000L) != 0L)
            return 11;
         return -1;
      case 7:
         if ((active0 & 0x20000000000000L) != 0L)
            return 11;
         if ((active0 & 0x18000000000000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 7;
            return 11;
         }
         return -1;
      case 8:
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 8;
            return 11;
         }
         if ((active0 & 0x10000000000000L) != 0L)
            return 11;
         return -1;
      case 9:
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 9;
            return 11;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 37:
         return jjStopAtPos(0, 12);
      case 40:
         return jjStopAtPos(0, 7);
      case 41:
         return jjStopAtPos(0, 8);
      case 42:
         return jjStopAtPos(0, 10);
      case 43:
         return jjStopAtPos(0, 13);
      case 44:
         return jjStopAtPos(0, 9);
      case 45:
         return jjStopAtPos(0, 14);
      case 46:
         return jjStartNfaWithStates_0(0, 6, 1);
      case 47:
         return jjStopAtPos(0, 11);
      case 59:
         return jjStopAtPos(0, 5);
      case 60:
         jjmatchedKind = 15;
         return jjMoveStringLiteralDfa1_0(0x410000L);
      case 61:
         jjmatchedKind = 20;
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 62:
         jjmatchedKind = 17;
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x800004004000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x1020000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x4080000000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x100008000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x102000000000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x200800000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800430000000L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x1000009000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0xa0000000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x10000180000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x48200001000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x400000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x2002000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(1, 16);
         else if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         else if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         else if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         break;
      case 62:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(1, 22);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x10600000800000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x81000188000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x40002000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000000L);
      case 78:
      case 110:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 36, 11);
         return jjMoveStringLiteralDfa2_0(active0, 0x802804430000000L);
      case 79:
      case 111:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 54, 11);
         return jjMoveStringLiteralDfa2_0(active0, 0x24000800000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 82:
      case 114:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1008190201000000L);
      case 83:
      case 115:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(1, 26, 11);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000000L);
      case 89:
      case 121:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 41, 11);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0xc08000000000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 68:
      case 100:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 38, 11);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 49, 11);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000800040000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x200082000000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0xa0400108800000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x4040000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x110200000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 84:
      case 116:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(2, 31, 11);
         return jjMoveStringLiteralDfa3_0(active0, 0x22000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x80040000000L);
      case 69:
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 11);
         return jjMoveStringLiteralDfa4_0(active0, 0x1090800518000000L);
      case 72:
      case 104:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 11);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x1040000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x920200000000000L);
      case 77:
      case 109:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 11);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000L);
      case 78:
      case 110:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 35, 11);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 58, 11);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L);
      case 79:
      case 111:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 11);
         break;
      case 80:
      case 112:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 11);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x200002000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x410000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x180000000000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L);
      case 69:
      case 101:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 23, 11);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 37, 11);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 45, 11);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000L);
      case 78:
      case 110:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 48, 11);
         break;
      case 80:
      case 112:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 40, 11);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000000L);
      case 82:
      case 114:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 11);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 60, 11);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L);
      case 84:
      case 116:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 11);
         return jjMoveStringLiteralDfa5_0(active0, 0x80048000000L);
      case 88:
      case 120:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 47, 11);
         break;
      case 89:
      case 121:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 57, 11);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x28000000000000L);
      case 69:
      case 101:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 11);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 11);
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 43, 11);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000000L);
      case 83:
      case 115:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 46, 11);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000000L);
      case 84:
      case 116:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 28, 11);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 11);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 50, 11);
         break;
      case 90:
      case 122:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x28000000000000L);
      case 69:
      case 101:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 55, 11);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 59, 11);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L);
      case 78:
      case 110:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 11);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 75:
      case 107:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 53, 11);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000L);
      case 84:
      case 116:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 52, 11);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 51, 11);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 33;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 61)
                        kind = 61;
                     { jjCheckNAddStates(0, 3); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(13, 15); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(4, 6); }
                  else if (curChar == 46)
                     { jjCheckNAdd(1); }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 3:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(4); }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAdd(4); }
                  break;
               case 5:
               case 7:
                  if (curChar == 39)
                     { jjCheckNAddStates(4, 6); }
                  break;
               case 6:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     { jjCheckNAddStates(4, 6); }
                  break;
               case 8:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 39 && kind > 65)
                     kind = 65;
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 12:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(13, 15); }
                  break;
               case 13:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 14:
                  if (curChar == 34)
                     { jjCheckNAddStates(7, 9); }
                  break;
               case 15:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 34 && kind > 66)
                     kind = 66;
                  break;
               case 18:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjAddStates(10, 12); }
                  break;
               case 23:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjAddStates(13, 14); }
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddStates(0, 3); }
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddStates(15, 17); }
                  break;
               case 27:
                  if (curChar != 46)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(28, 29); }
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAddTwoStates(28, 29); }
                  break;
               case 30:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(31); }
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  { jjCheckNAdd(31); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  { jjCheckNAdd(32); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 66)
                        kind = 66;
                     { jjCheckNAdd(11); }
                  }
                  else if (curChar == 91)
                     { jjCheckNAdd(23); }
                  else if (curChar == 96)
                     { jjCheckNAddTwoStates(18, 20); }
                  break;
               case 2:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(18, 19); }
                  break;
               case 6:
                  { jjAddStates(4, 6); }
                  break;
               case 10:
               case 11:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAdd(11); }
                  break;
               case 13:
                  { jjAddStates(7, 9); }
                  break;
               case 17:
                  if (curChar == 96)
                     { jjCheckNAddTwoStates(18, 20); }
                  break;
               case 18:
                  if ((0xfffffffeffffffffL & l) != 0L)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 19:
                  if (curChar == 96)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 20:
                  if (curChar == 96)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 96 && kind > 66)
                     kind = 66;
                  break;
               case 22:
                  if (curChar == 91)
                     { jjCheckNAdd(23); }
                  break;
               case 23:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 24:
                  if (curChar == 93 && kind > 66)
                     kind = 66;
                  break;
               case 29:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(20, 21); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 6:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(4, 6); }
                  break;
               case 13:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(7, 9); }
                  break;
               case 18:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(10, 12); }
                  break;
               case 23:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(13, 14); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 33 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\73", "\56", "\50", "\51", "\54", "\52", "\57", 
"\45", "\53", "\55", "\74", "\74\75", "\76", "\76\75", "\75\75", "\75", "\41\75", 
"\74\76", null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   26, 27, 29, 32, 6, 8, 9, 13, 15, 16, 18, 20, 21, 23, 24, 26, 
   27, 29, 3, 4, 30, 31, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public RookieParserTokenManager(SimpleCharStream stream){
      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public RookieParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 33; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x7fffffffffffffe1L, 0x6L, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[33];
    private final int[] jjstateSet = new int[2 * 33];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
