/* Generated By:JavaCC: Do not edit this line. RookieParserVisitor.java Version 7.0.5 */
package edu.berkeley.cs186.database.cli.parser;

public interface RookieParserVisitor
{
  public void visit(SimpleNode node, Object data);
  public void visit(ASTSQLStatementList node, Object data);
  public void visit(ASTExplainStatement node, Object data);
  public void visit(ASTDropTableStatement node, Object data);
  public void visit(ASTDropIndexStatement node, Object data);
  public void visit(ASTReleaseStatement node, Object data);
  public void visit(ASTSavepointStatement node, Object data);
  public void visit(ASTRollbackStatement node, Object data);
  public void visit(ASTBeginStatement node, Object data);
  public void visit(ASTCommitStatement node, Object data);
  public void visit(ASTInsertStatement node, Object data);
  public void visit(ASTSelectStatement node, Object data);
  public void visit(ASTDeleteStatement node, Object data);
  public void visit(ASTCreateTableStatement node, Object data);
  public void visit(ASTCreateIndexStatement node, Object data);
  public void visit(ASTColumnDef node, Object data);
  public void visit(ASTSelectClause node, Object data);
  public void visit(ASTLimit node, Object data);
  public void visit(ASTFromClause node, Object data);
  public void visit(ASTJoinedTable node, Object data);
  public void visit(ASTResultColumnName node, Object data);
  public void visit(ASTColumnName node, Object data);
  public void visit(ASTTableName node, Object data);
  public void visit(ASTIdentifier node, Object data);
  public void visit(ASTAliasedTableName node, Object data);
  public void visit(ASTBinaryExpression node, Object data);
  public void visit(ASTLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=c56d70518ba0a00c6638e250c2dcb4c5 (do not edit this line) */
