/* Generated By:JavaCC: Do not edit this line. RookieParserTreeConstants.java Version 7.0.5 */
package edu.berkeley.cs186.database.cli.parser;

public interface RookieParserTreeConstants
{
  public int JJTSQLSTATEMENTLIST = 0;
  public int JJTVOID = 1;
  public int JJTEXPLAINSTATEMENT = 2;
  public int JJTDROPTABLESTATEMENT = 3;
  public int JJTDROPINDEXSTATEMENT = 4;
  public int JJTRELEASESTATEMENT = 5;
  public int JJTSAVEPOINTSTATEMENT = 6;
  public int JJTROLLBACKSTATEMENT = 7;
  public int JJTBEGINSTATEMENT = 8;
  public int JJTCOMMITSTATEMENT = 9;
  public int JJTINSERTSTATEMENT = 10;
  public int JJTSELECTSTATEMENT = 11;
  public int JJTDELETESTATEMENT = 12;
  public int JJTCREATETABLESTATEMENT = 13;
  public int JJTCREATEINDEXSTATEMENT = 14;
  public int JJTCOLUMNDEF = 15;
  public int JJTSELECTCLAUSE = 16;
  public int JJTLIMIT = 17;
  public int JJTFROMCLAUSE = 18;
  public int JJTJOINEDTABLE = 19;
  public int JJTRESULTCOLUMNNAME = 20;
  public int JJTCOLUMNNAME = 21;
  public int JJTTABLENAME = 22;
  public int JJTIDENTIFIER = 23;
  public int JJTALIASEDTABLENAME = 24;
  public int JJTBINARYEXPRESSION = 25;
  public int JJTLITERAL = 26;

  public String[] jjtNodeName = {
    "SQLStatementList",
    "void",
    "ExplainStatement",
    "DropTableStatement",
    "DropIndexStatement",
    "ReleaseStatement",
    "SavepointStatement",
    "RollbackStatement",
    "BeginStatement",
    "CommitStatement",
    "InsertStatement",
    "SelectStatement",
    "DeleteStatement",
    "CreateTableStatement",
    "CreateIndexStatement",
    "ColumnDef",
    "SelectClause",
    "Limit",
    "FromClause",
    "JoinedTable",
    "ResultColumnName",
    "ColumnName",
    "TableName",
    "Identifier",
    "AliasedTableName",
    "BinaryExpression",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=89417c3b8da500b2f11a29bcc29e31a0 (do not edit this line) */
